create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  created_at timestamptz not null default now()
);

insert into public.app_users (username, password)
values ('admin', 'chomart12')
on conflict (username) do update
set password = excluded.password;;
