create table if not exists public.medicines (
  id bigint generated by default as identity primary key,
  name text not null,
  dosage text,
  expiry_days integer,
  price numeric(10,2) not null default 0,
  pack_quantity integer not null default 0,
  minimum_stock integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.medicines enable row level security;

do $$ begin
  create policy "Allow read for authenticated users" on public.medicines
    for select to authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Allow insert for authenticated users" on public.medicines
    for insert to authenticated with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Allow update for authenticated users" on public.medicines
    for update to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;;
