create extension if not exists pgcrypto;

create table if not exists medications (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  daily_dose_pills numeric(10,2) not null default 1 check (daily_dose_pills > 0),
  pills_per_box numeric(10,2) not null default 1 check (pills_per_box > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists stock_lots (
  id uuid primary key default gen_random_uuid(),
  lot_number bigint generated by default as identity,
  lot_code text unique,
  medication_id uuid not null references medications(id) on delete cascade,
  quantity_pills_original integer not null check (quantity_pills_original >= 0),
  quantity_pills_remaining integer not null check (quantity_pills_remaining >= 0),
  expiry_month integer not null check (expiry_month between 1 and 12),
  expiry_year integer not null check (expiry_year between 2000 and 2100),
  total_price numeric(12,2) not null check (total_price >= 0),
  cost_per_pill numeric(12,4) not null check (cost_per_pill >= 0),
  standard_box_price numeric(12,2) not null check (standard_box_price >= 0),
  created_at timestamptz not null default now()
);

create table if not exists stock_history (
  id uuid primary key default gen_random_uuid(),
  medication_id uuid not null references medications(id) on delete cascade,
  stock_lot_id uuid references stock_lots(id) on delete set null,
  type text not null check (type in ('add_stock', 'recount_stock')),
  quantity_pills integer not null check (quantity_pills >= 0),
  price numeric(12,2),
  expiry_month integer,
  expiry_year integer,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists app_settings (
  id uuid primary key default gen_random_uuid(),
  low_stock_alert_days integer not null default 14 check (low_stock_alert_days between 1 and 365),
  expiring_lot_alert_days integer not null default 90 check (expiring_lot_alert_days between 1 and 730),
  pin_value text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_stock_lots_medication_id on stock_lots(medication_id);
create index if not exists idx_stock_lots_expiry on stock_lots(expiry_year, expiry_month);
create index if not exists idx_stock_history_medication_id on stock_history(medication_id);
create index if not exists idx_stock_history_created_at on stock_history(created_at desc);

create or replace function set_lot_code()
returns trigger
language plpgsql
as $$
begin
  if new.lot_code is null then
    new.lot_code := 'Lot #' || lpad(new.lot_number::text, 3, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_lot_code on stock_lots;
create trigger trg_set_lot_code
before insert on stock_lots
for each row execute function set_lot_code();

alter table medications enable row level security;
alter table stock_lots enable row level security;
alter table stock_history enable row level security;
alter table app_settings enable row level security;

drop policy if exists "personal app read medications" on medications;
drop policy if exists "personal app write medications" on medications;
drop policy if exists "personal app read stock_lots" on stock_lots;
drop policy if exists "personal app write stock_lots" on stock_lots;
drop policy if exists "personal app read stock_history" on stock_history;
drop policy if exists "personal app write stock_history" on stock_history;
drop policy if exists "personal app read app_settings" on app_settings;
drop policy if exists "personal app write app_settings" on app_settings;

create policy "personal app read medications" on medications for select using (true);
create policy "personal app write medications" on medications for all using (true) with check (true);
create policy "personal app read stock_lots" on stock_lots for select using (true);
create policy "personal app write stock_lots" on stock_lots for all using (true) with check (true);
create policy "personal app read stock_history" on stock_history for select using (true);
create policy "personal app write stock_history" on stock_history for all using (true) with check (true);
create policy "personal app read app_settings" on app_settings for select using (true);
create policy "personal app write app_settings" on app_settings for all using (true) with check (true);
